-- Tạo bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    ChucVu VARCHAR2(50),
    TenDangNhap VARCHAR2(50),
    MatKhau VARCHAR2(50)
);

-- Tạo bảng HIEUXE
CREATE TABLE HIEUXE (
    MaHX VARCHAR2(50) PRIMARY KEY,
    TenHieuXe VARCHAR2(50)
);

-- Tạo bảng TIENCONG
CREATE TABLE TIENCONG (
    MaTC VARCHAR2(50) PRIMARY KEY,
    TenTC VARCHAR2(50),
    ChiPhiTC NUMBER(10, 2)
);

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR2(50) PRIMARY KEY,
    HoTenKH VARCHAR2(50),
    DienThoai NUMBER(10),
    EMail VARCHAR2(50),
    DiaChi VARCHAR2(50)
);

-- Tạo bảng XE
CREATE TABLE XE (
    BienSo VARCHAR2(50) PRIMARY KEY,
    MaHX VARCHAR2(50) REFERENCES HIEUXE(MaHX),
    MaKH VARCHAR2(50) REFERENCES KHACHHANG(MaKH),
    TienNo NUMBER(10, 2),
    NgayTiepNhan DATE
);

-- Tạo bảng PHIEUTHUTIEN
CREATE TABLE PHIEUTHUTIEN (
    MaPhieuThuTien VARCHAR2(50) PRIMARY KEY,
    BienSo VARCHAR2(50) REFERENCES XE(BienSo),
    SoTienThu NUMBER(10, 2),
    NgayThuTien DATE
);

-- Tạo bảng PHIEUSUACHUA
CREATE TABLE PHIEUSUACHUA (
    MaPhieuSuaChua VARCHAR2(50) PRIMARY KEY,
    BienSo VARCHAR2(50) REFERENCES XE(BienSo),
    NgaySuaChua DATE,
    ThanhTienPSC NUMBER(10, 2)
);

-- Tạo bảng CT_PHIEUSUACHUA
CREATE TABLE CT_PHIEUSUACHUA (
    MaCTPSC VARCHAR2(50) PRIMARY KEY,
    MaPSC VARCHAR2(50) REFERENCES PHIEUSUACHUA(MaPhieuSuaChua),
    MaTC VARCHAR2(50) REFERENCES TIENCONG(MaTC),
    NoiDung VARCHAR2(50),
    ThanhTienND NUMBER(10, 2)
);

-- Tạo bảng CT_SUDUNGVTPT
CREATE TABLE CT_SUDUNGVTPT (
    MaCTPSC VARCHAR2(50),
    MaVTPT VARCHAR2(50),
    SoLuongSuDung NUMBER(10),
    ThanhTien NUMBER(10, 2),
    PRIMARY KEY (MaCTPSC, MaVTPT),
    FOREIGN KEY (MaCTPSC) REFERENCES CT_PHIEUSUACHUA(MaCTPSC),
    FOREIGN KEY (MaVTPT) REFERENCES VATTUPHUTUNG(MaVTPT)
);

-- Tạo bảng VATTUPHUTUNG
CREATE TABLE VATTUPHUTUNG (
    MaVTPT VARCHAR2(50) PRIMARY KEY,
    TenVTPT VARCHAR2(50),
    DonGiaNhap NUMBER(10, 2),
    DonGiaBan NUMBER(10, 2),
    SoLuongTon NUMBER(10)
);

-- Tạo bảng PHIEUNHAPVTPT
CREATE TABLE PHIEUNHAPVTPT (
    MaPNVTPT VARCHAR2(50) PRIMARY KEY,
    ThanhTienNhap NUMBER(10, 2),
    NgayNhap DATE
);

-- Tạo bảng CT_PHIEUNHAPVTPT
CREATE TABLE CT_PHIEUNHAPVTPT (
    MaPNVTPT VARCHAR2(50),
    MaVTPT VARCHAR2(50),
    SoLuongNhap NUMBER(10),
    TienNhapVTPT NUMBER(10, 2),
    PRIMARY KEY (MaPNVTPT, MaVTPT),
    FOREIGN KEY (MaPNVTPT) REFERENCES PHIEUNHAPVTPT(MaPNVTPT),
    FOREIGN KEY (MaVTPT) REFERENCES VATTUPHUTUNG(MaVTPT)
);

-- Tạo bảng BAOCAODOANHSO
CREATE TABLE BAOCAODOANHSO (
    MaBCDS VARCHAR2(50) PRIMARY KEY,
    Thang NUMBER(2),
    Nam NUMBER(4),
    TongDoanhThu NUMBER(10, 2)
);

-- Tạo bảng CT_BAOCAODOANHSO
CREATE TABLE CT_BAOCAODOANHSO (
    MaBCDS VARCHAR2(50),
    MaHX VARCHAR2(50),
    SoLuotSua NUMBER(10),
    ThanhTien NUMBER(10, 2),
    TiLe NUMBER(5, 2),
    PRIMARY KEY (MaBCDS, MaHX),
    FOREIGN KEY (MaBCDS) REFERENCES BAOCAODOANHSO(MaBCDS),
    FOREIGN KEY (MaHX) REFERENCES HIEUXE(MaHX)
);

-- Tạo bảng BAOCAOTON
CREATE TABLE BAOCAOTON (
    MaVTPT VARCHAR2(50),
    Thang NUMBER(2),
    Nam NUMBER(4),
    TonDau NUMBER(10),
    TonCuoi NUMBER(10),
    PhatSinh NUMBER(10),
    PRIMARY KEY (MaVTPT, Thang, Nam),
    FOREIGN KEY (MaVTPT) REFERENCES VATTUPHUTUNG(MaVTPT)
);

-- Tạo bảng THAMSO
CREATE TABLE THAMSO (
    TenThamSo VARCHAR2(50) PRIMARY KEY,
    GiaTri NUMBER(10)
);

INSERT INTO TAIKHOAN (ChucVu, TenDangNhap, MatKhau) VALUES ('Quan Ly', 'VoDinhMinhQuan', '22521193');
INSERT INTO TAIKHOAN (ChucVu, TenDangNhap, MatKhau) VALUES ('Quản lý', 'admin', '1');
select * from TAIKHOAN;
select * from TAIKHOAN WHERE TENDANGNHAP = 'VoDinhMinhQuan';
SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = 'VoDinhMinhQuan';
SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = 'VoDinhMinhQuan';
