-- Tạo bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    ChucVu VARCHAR2(50),
    TenDangNhap VARCHAR2(50),
    MatKhau VARCHAR2(50)
);

-- Tạo bảng TIENCONG
CREATE TABLE TIENCONG (
    MaTC VARCHAR2(50) PRIMARY KEY,
    TenTC VARCHAR2(50),
    ChiPhiTC NUMBER(10, 2)
);

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR2(50) PRIMARY KEY,
    HoTenKH VARCHAR2(50),
    DienThoai NUMBER(10),
    EMail VARCHAR2(50)
);


-- Tạo bảng XE
CREATE TABLE XE (
    BienSo VARCHAR2(50) PRIMARY KEY,
    MaKH VARCHAR2(50) REFERENCES KHACHHANG(MaKH),
    tenHX VARCHAR(20),
    TienNo NUMBER(10, 2),
    NgayTiepNhan DATE
);

-- Tạo bảng PHIEUTHUTIEN
CREATE TABLE PHIEUTHUTIEN (
    MaPhieuThuTien VARCHAR2(50) PRIMARY KEY,
    BienSo VARCHAR2(50) REFERENCES XE(BienSo),
    SoTienThu NUMBER(10, 2),
    NgayThuTien DATE
);

-- Tạo bảng PHIEUSUACHUA
CREATE TABLE PHIEUSUACHUA (
    MaPhieuSuaChua VARCHAR2(50) PRIMARY KEY,
    BienSo VARCHAR2(50) REFERENCES XE(BienSo),
    NgaySuaChua DATE,
    ThanhTienPSC NUMBER(10, 2)
);

-- Tạo bảng VATTUPHUTUNG
CREATE TABLE VATTUPHUTUNG (
    MaVTPT VARCHAR2(50) PRIMARY KEY,
    TenVTPT VARCHAR2(50),
    DonGiaNhap NUMBER(10, 2),
    DonGiaBan NUMBER(10, 2),
    SoLuongTon NUMBER(10)
);


-- Tạo bảng CT_SUDUNGVTPT
CREATE TABLE CT_SUDUNGVTPT (
    MaPhieuSuaChua VARCHAR2(50),
    MaVTPT VARCHAR2(50),
    SoLuongSuDung NUMBER(10),
    ThanhTien NUMBER(10, 2),
    PRIMARY KEY (MaPhieuSuaChua, MaVTPT),
    FOREIGN KEY (MaPhieuSuaChua) REFERENCES PHIEUSUACHUA(MaPhieuSuaChua),
    FOREIGN KEY (MaVTPT) REFERENCES VATTUPHUTUNG(MaVTPT)
);

-- Tạo bảng PHIEUNHAPVTPT
CREATE TABLE PHIEUNHAPVTPT (
    MaPNVTPT VARCHAR2(50) PRIMARY KEY,
    ThanhTienNhap NUMBER(10, 2),
    NgayNhap DATE
);


-- Tạo bảng CT_PHIEUNHAPVTPT
CREATE TABLE CT_PHIEUNHAPVTPT (
    MaPNVTPT VARCHAR2(50),
    MaVTPT VARCHAR2(50),
    SoLuongNhap NUMBER(10),
    TienNhapVTPT NUMBER(10, 2),
    PRIMARY KEY (MaPNVTPT, MaVTPT),
    FOREIGN KEY (MaPNVTPT) REFERENCES PHIEUNHAPVTPT(MaPNVTPT),
    FOREIGN KEY (MaVTPT) REFERENCES VATTUPHUTUNG(MaVTPT)
);

-- Tạo bảng BAOCAODOANHSO
CREATE TABLE BAOCAODOANHSO (
    MaBCDS VARCHAR2(50) PRIMARY KEY,
    Thang NUMBER(2),
    Nam NUMBER(4),
    TongDoanhThu NUMBER(10, 2)
);


-- T?o sequence cho b?ng KHACHHANG
CREATE SEQUENCE KHACHHANG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE SEQ_MAVTPT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MAPNVTPT START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_VTPT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PNVTPT START WITH 1 INCREMENT BY 1;


INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC01', 'Thay dầu động cơ', 500000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC02', 'Bảo dưỡng phanh', 700000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC03', 'Thay bugi', 300000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC04', 'Sửa chữa hộp số', 1500000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC05', 'Thay l�?c gió', 200000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC06', 'Kiểm tra ắc quy', 100000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC07', 'Bảo dưỡng hệ thống điện', 800000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC08', 'Sửa chữa đi�?u hòa', 1200000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC09', 'Thay nước làm mát', 400000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC10', 'Bảo dưỡng khung gầm', 900000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC11', 'Sửa chữa hệ thống lái', 1100000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC12', 'Thay l�?c dầu', 450000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC13', 'Bảo dưỡng hệ thống treo', 1000000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC14', 'Thay lốp xe', 550000);
INSERT INTO TIENCONG (MaTC, TenTC, ChiPhiTC) VALUES ('TC15', 'Sửa chữa động cơ', 2000000);

COMMIT;

CREATE SEQUENCE MaPhieuSuaChua_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE SEQUENCE MaPhieuThuTien_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


